// 시장 화면용 주요 종목 목록 (국내/해외). symbol=네이버 reutersCode로 시세/차트 바로 조회.
export interface MarketStock {
  name: string; // 한글 종목명
  ticker: string; // 표시용 (국내 6자리, 미국 티커)
  symbol: string; // 네이버 심볼 (국내=6자리, 미국=NVDA.O 등)
  market: string; // KOSPI/KOSDAQ/NASDAQ/NYSE
  domestic: boolean;
}

// 국내 대표주 (코드=심볼, 국내 시세 직접 조회)
export const KR_STOCKS: MarketStock[] = [
  ["삼성전자", "005930", "KOSPI"],
  ["SK하이닉스", "000660", "KOSPI"],
  ["LG에너지솔루션", "373220", "KOSPI"],
  ["삼성바이오로직스", "207940", "KOSPI"],
  ["현대차", "005380", "KOSPI"],
  ["기아", "000270", "KOSPI"],
  ["셀트리온", "068270", "KOSPI"],
  ["NAVER", "035420", "KOSPI"],
  ["카카오", "035720", "KOSPI"],
  ["POSCO홀딩스", "005490", "KOSPI"],
  ["LG화학", "051910", "KOSPI"],
  ["삼성SDI", "006400", "KOSPI"],
  ["현대모비스", "012330", "KOSPI"],
  ["KB금융", "105560", "KOSPI"],
  ["신한지주", "055550", "KOSPI"],
  ["한화에어로스페이스", "012450", "KOSPI"],
  ["HD현대중공업", "329180", "KOSPI"],
  ["두산에너빌리티", "034020", "KOSPI"],
  ["크래프톤", "259960", "KOSPI"],
  ["알테오젠", "196170", "KOSDAQ"],
  ["에코프로비엠", "247540", "KOSDAQ"],
].map(([name, code, market]) => ({
  name,
  ticker: code,
  symbol: code,
  market,
  domestic: true,
}));

// 해외(미국) 대표주 — symbol은 검증된 네이버 reutersCode
export const US_STOCKS: MarketStock[] = [
  ["엔비디아", "NVDA", "NVDA.O", "NASDAQ"],
  ["애플", "AAPL", "AAPL.O", "NASDAQ"],
  ["마이크로소프트", "MSFT", "MSFT.O", "NASDAQ"],
  ["알파벳", "GOOGL", "GOOGL.O", "NASDAQ"],
  ["아마존", "AMZN", "AMZN.O", "NASDAQ"],
  ["메타", "META", "META.O", "NASDAQ"],
  ["테슬라", "TSLA", "TSLA.O", "NASDAQ"],
  ["브로드컴", "AVGO", "AVGO.O", "NASDAQ"],
  ["TSMC", "TSM", "TSM", "NYSE"],
  ["넷플릭스", "NFLX", "NFLX.O", "NASDAQ"],
  ["AMD", "AMD", "AMD.O", "NASDAQ"],
  ["팔란티어", "PLTR", "PLTR.O", "NASDAQ"],
  ["마이크론", "MU", "MU.O", "NASDAQ"],
  ["코인베이스", "COIN", "COIN.O", "NASDAQ"],
  ["인텔", "INTC", "INTC.O", "NASDAQ"],
  ["퀄컴", "QCOM", "QCOM.O", "NASDAQ"],
  ["마이크로스트래티지", "MSTR", "MSTR.O", "NASDAQ"],
  ["알리바바", "BABA", "BABA.K", "NYSE"],
  // ── 아래는 네이버 자동완성으로 심볼을 검증한 목록 (reutersCode 실측) ──
  ["JP모건", "JPM", "JPM", "NYSE"],
  ["뱅크오브아메리카", "BAC", "BAC", "NYSE"],
  ["웰스파고", "WFC", "WFC", "NYSE"],
  ["골드만삭스", "GS", "GS", "NYSE"],
  ["모건스탠리", "MS", "MS", "NYSE"],
  ["씨티그룹", "C", "C", "NYSE"],
  ["블랙록", "BLK", "BLK", "NYSE"],
  ["찰스슈왑", "SCHW", "SCHW.K", "NYSE"],
  ["아메리칸익스프레스", "AXP", "AXP", "NYSE"],
  ["비자", "V", "V", "NYSE"],
  ["마스터카드", "MA", "MA", "NYSE"],
  ["페이팔", "PYPL", "PYPL.O", "NASDAQ"],
  ["존슨앤드존슨", "JNJ", "JNJ", "NYSE"],
  ["유나이티드헬스", "UNH", "UNH", "NYSE"],
  ["일라이릴리", "LLY", "LLY", "NYSE"],
  ["화이자", "PFE", "PFE", "NYSE"],
  ["머크", "MRK", "MRK", "NYSE"],
  ["애브비", "ABBV", "ABBV.K", "NYSE"],
  ["써모피셔", "TMO", "TMO", "NYSE"],
  ["애보트", "ABT", "ABT", "NYSE"],
  ["암젠", "AMGN", "AMGN.O", "NASDAQ"],
  ["월마트", "WMT", "WMT.O", "NASDAQ"],
  ["코스트코", "COST", "COST.O", "NASDAQ"],
  ["홈디포", "HD", "HD", "NYSE"],
  ["맥도날드", "MCD", "MCD", "NYSE"],
  ["나이키", "NKE", "NKE", "NYSE"],
  ["스타벅스", "SBUX", "SBUX.O", "NASDAQ"],
  ["P&G", "PG", "PG", "NYSE"],
  ["코카콜라", "KO", "KO", "NYSE"],
  ["펩시코", "PEP", "PEP.O", "NASDAQ"],
  ["디즈니", "DIS", "DIS", "NYSE"],
  ["엑슨모빌", "XOM", "XOM", "NYSE"],
  ["셰브론", "CVX", "CVX", "NYSE"],
  ["코노코필립스", "COP", "COP", "NYSE"],
  ["캐터필러", "CAT", "CAT", "NYSE"],
  ["GE에어로스페이스", "GE", "GE", "NYSE"],
  ["록히드마틴", "LMT", "LMT", "NYSE"],
  ["RTX", "RTX", "RTX", "NYSE"],
  ["UPS", "UPS", "UPS", "NYSE"],
  ["유니온퍼시픽", "UNP", "UNP", "NYSE"],
  ["포드", "F", "F", "NYSE"],
  ["제너럴모터스", "GM", "GM", "NYSE"],
  ["AT&T", "T", "T", "NYSE"],
  ["버라이즌", "VZ", "VZ", "NYSE"],
  ["컴캐스트", "CMCSA", "CMCSA.O", "NASDAQ"],
  ["필립모리스", "PM", "PM", "NYSE"],
  ["오라클", "ORCL", "ORCL.K", "NYSE"],
  ["세일즈포스", "CRM", "CRM", "NYSE"],
  ["어도비", "ADBE", "ADBE.O", "NASDAQ"],
  ["시스코", "CSCO", "CSCO.O", "NASDAQ"],
  ["IBM", "IBM", "IBM", "NYSE"],
  ["서비스나우", "NOW", "NOW", "NYSE"],
  ["텍사스인스트루먼트", "TXN", "TXN.O", "NASDAQ"],
  ["어플라이드머티어리얼즈", "AMAT", "AMAT.O", "NASDAQ"],
  ["램리서치", "LRCX", "LRCX.O", "NASDAQ"],
  ["KLA", "KLAC", "KLAC.O", "NASDAQ"],
  ["ARM", "ARM", "ARM.O", "NASDAQ"],
  ["슈퍼마이크로", "SMCI", "SMCI.O", "NASDAQ"],
  ["ASML", "ASML", "ASML.O", "NASDAQ"],
  ["델테크놀로지", "DELL", "DELL.K", "NYSE"],
  ["우버", "UBER", "UBER.K", "NYSE"],
  ["에어비앤비", "ABNB", "ABNB.O", "NASDAQ"],
  ["쇼피파이", "SHOP", "SHOP.O", "NASDAQ"],
  ["팔로알토네트웍스", "PANW", "PANW.O", "NASDAQ"],
  ["크라우드스트라이크", "CRWD", "CRWD.O", "NASDAQ"],
  ["마벨", "MRVL", "MRVL.O", "NASDAQ"],
  ["아날로그디바이스", "ADI", "ADI.O", "NASDAQ"],
].map(([name, ticker, symbol, market]) => ({
  name,
  ticker,
  symbol,
  market,
  domestic: false,
}));
