import type { Source } from "./types";

// 입장 전 최소 팔로우 개수 (트루스소셜식 온보딩 게이트)
export const MIN_FOLLOW = 5;

// 검증된(살아있는) 증권·금융 특화 RSS 피드만 등록.
// 새 소스를 추가하려면 여기에 한 줄 추가하면 됩니다.
export const SOURCES: Source[] = [
  // ── 국내 🇰🇷 ──
  {
    id: "hankyung",
    name: "한국경제",
    handle: "@hankyung",
    category: "증권·금융",
    region: "kr",
    // ⚠️ hankyung.com RSS(/feed/*)가 Cloudflare 봇차단(403)됨(2026-07-08). 기사 페이지는
    // 정상이라 구글뉴스 site: 검색으로 헤드라인 받고 → 리더가 실제 URL 해석해 본문 추출.
    url: "https://news.google.com/rss/search?q=site%3Ahankyung.com%20(%EC%A6%9D%EC%8B%9C%20OR%20%EC%A3%BC%EC%8B%9D%20OR%20%EC%BD%94%EC%8A%A4%ED%94%BC%20OR%20%EC%A2%85%EB%AA%A9%20OR%20%EC%A3%BC%EA%B0%80)%20when%3A3d&hl=ko&gl=KR&ceid=KR:ko",
    domain: "hankyung.com",
    color: "#00355f",
  },
  {
    id: "yna",
    name: "연합뉴스",
    handle: "@yonhap",
    category: "증시",
    region: "kr",
    url: "https://www.yna.co.kr/rss/market.xml",
    domain: "yna.co.kr",
    color: "#1a4f9c",
  },
  {
    id: "edaily",
    name: "이데일리",
    handle: "@edaily",
    category: "증권",
    region: "kr",
    url: "http://rss.edaily.co.kr/stock_news.xml",
    domain: "edaily.co.kr",
    color: "#0b4da2",
  },
  {
    id: "chosunbiz",
    name: "조선비즈",
    handle: "@chosunbiz",
    category: "증권",
    region: "kr",
    url: "https://biz.chosun.com/arc/outboundfeeds/rss/category/stock/?outputType=xml",
    domain: "biz.chosun.com",
    color: "#004b9b",
  },
  {
    id: "fnnews",
    name: "파이낸셜뉴스",
    handle: "@fnnews",
    category: "증권",
    region: "kr",
    url: "https://www.fnnews.com/rss/r20/fn_realnews_stock.xml",
    domain: "fnnews.com",
    color: "#d31145",
  },
  {
    id: "mk",
    name: "매일경제",
    handle: "@maekyung",
    category: "증권",
    region: "kr",
    url: "https://www.mk.co.kr/rss/50200011/",
    domain: "mk.co.kr",
    color: "#d8232a",
  },
  {
    id: "asiae",
    name: "아시아경제",
    handle: "@asiae",
    category: "증권",
    region: "kr",
    url: "https://www.asiae.co.kr/rss/stock.htm",
    domain: "asiae.co.kr",
    color: "#0b8a3d",
  },
  {
    id: "einfomax",
    name: "연합인포맥스",
    handle: "@einfomax",
    category: "금융·채권",
    region: "kr",
    url: "https://news.einfomax.co.kr/rss/clickTop.xml",
    domain: "einfomax.co.kr",
    color: "#003a70",
  },
  // ── 해외 🌐 ──
  // (Investing.com 제거 — 사이트가 봇 차단(Cloudflare)으로 본문·요약을 전혀 안 줘
  //  인앱에서 못 읽고 항상 원문 이동만 됨. 2026-07-04)
  {
    id: "cnbc",
    name: "CNBC Markets",
    handle: "@CNBC",
    category: "Markets",
    region: "global",
    url: "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    domain: "cnbc.com",
    color: "#005594",
  },
  {
    id: "yahoo",
    name: "Yahoo Finance",
    handle: "@YahooFinance",
    category: "Finance",
    region: "global",
    url: "https://finance.yahoo.com/news/rssindex",
    domain: "finance.yahoo.com",
    color: "#6001d2",
  },
  {
    id: "seekingalpha",
    name: "Seeking Alpha",
    handle: "@SeekingAlpha",
    category: "Stock Analysis",
    region: "global",
    url: "https://seekingalpha.com/feed.xml",
    domain: "seekingalpha.com",
    color: "#ff6600",
  },
  {
    id: "nasdaq",
    name: "Nasdaq",
    handle: "@Nasdaq",
    category: "Markets",
    region: "global",
    url: "https://www.nasdaq.com/feed/rssoutbound?category=Markets",
    domain: "nasdaq.com",
    color: "#0092cf",
  },
  {
    id: "businessinsider",
    name: "Business Insider",
    handle: "@BInsider",
    category: "Markets",
    region: "global",
    url: "https://markets.businessinsider.com/rss/news",
    domain: "businessinsider.com",
    color: "#2255ff",
  },
  {
    id: "fool",
    name: "Motley Fool",
    handle: "@themotleyfool",
    category: "Investing",
    region: "global",
    url: "https://www.fool.com/feeds/index.aspx",
    domain: "fool.com",
    color: "#5a2d82",
  },
  {
    id: "bbc",
    name: "BBC Business",
    handle: "@BBCBusiness",
    category: "Business",
    region: "global",
    url: "https://feeds.bbci.co.uk/news/business/rss.xml",
    domain: "bbc.com",
    color: "#bb1919",
  },
  {
    id: "fortune",
    name: "Fortune",
    handle: "@FortuneMagazine",
    category: "Business",
    region: "global",
    url: "https://fortune.com/feed/",
    domain: "fortune.com",
    color: "#b08d2a",
  },
  // ── 신규 추가(2026-07-04) — 프로덕션에서 본문 추출 검증한 소스만 ──
  {
    id: "npr",
    name: "NPR Business",
    handle: "@NPR",
    category: "Business",
    region: "global",
    url: "https://feeds.npr.org/1006/rss.xml",
    domain: "npr.org",
    color: "#d0122b",
  },
  {
    id: "guardian",
    name: "The Guardian",
    handle: "@guardian",
    category: "Business",
    region: "global",
    url: "https://www.theguardian.com/business/rss",
    domain: "theguardian.com",
    color: "#052962",
  },
  {
    id: "coindesk",
    name: "CoinDesk",
    handle: "@CoinDesk",
    category: "Crypto",
    region: "global",
    url: "https://www.coindesk.com/arc/outboundfeeds/rss/",
    domain: "coindesk.com",
    color: "#f5b60c",
  },
  {
    id: "truthsocial",
    name: "Truth Social",
    handle: "@realDonaldTrump",
    category: "트럼프",
    region: "global",
    url: "https://trumpstruth.org/feed",
    domain: "truthsocial.com",
    color: "#5448ee",
  },
  // ── 외부 집계(숨김) — 팔로우 목록엔 안 뜨고 "속보"에만 사용 ──
  {
    id: "gnews_kr",
    name: "Google 뉴스",
    handle: "@GoogleNews",
    category: "속보",
    region: "kr",
    url: "https://news.google.com/rss/search?q=%EC%A6%9D%EC%8B%9C&hl=ko&gl=KR&ceid=KR:ko",
    domain: "news.google.com",
    color: "#4285f4",
    hidden: true,
  },
  {
    id: "gnews_us",
    name: "Google News",
    handle: "@GoogleNews",
    category: "Breaking",
    region: "global",
    url: "https://news.google.com/rss/search?q=stock%20market&hl=en-US&gl=US&ceid=US:en",
    domain: "news.google.com",
    color: "#4285f4",
    hidden: true,
  },
];

// 팔로우 가능한(사용자에게 보이는) 소스 — 숨김 제외
export const FOLLOWABLE = SOURCES.filter((s) => !s.hidden);

export const SOURCE_MAP: Record<string, Source> = Object.fromEntries(
  SOURCES.map((s) => [s.id, s]),
);

export function sourcesByIds(ids: string[]): Source[] {
  return ids.map((id) => SOURCE_MAP[id]).filter(Boolean);
}
