import type { Source } from "./types";

// 입장 전 최소 팔로우 개수 (트루스소셜식 온보딩 게이트)
export const MIN_FOLLOW = 5;

// 검증된(살아있는) 증권·금융 특화 RSS 피드만 등록.
// 새 소스를 추가하려면 여기에 한 줄 추가하면 됩니다.
export const SOURCES: Source[] = [
  // ── 국내 🇰🇷 ──
  {
    id: "hankyung",
    name: "한국경제",
    handle: "@hankyung",
    category: "증권·금융",
    region: "kr",
    url: "https://www.hankyung.com/feed/finance",
    domain: "hankyung.com",
    color: "#00355f",
  },
  {
    id: "yna",
    name: "연합뉴스",
    handle: "@yonhap",
    category: "증시",
    region: "kr",
    url: "https://www.yna.co.kr/rss/market.xml",
    domain: "yna.co.kr",
    color: "#1a4f9c",
  },
  {
    id: "edaily",
    name: "이데일리",
    handle: "@edaily",
    category: "증권",
    region: "kr",
    url: "http://rss.edaily.co.kr/stock_news.xml",
    domain: "edaily.co.kr",
    color: "#0b4da2",
  },
  {
    id: "chosunbiz",
    name: "조선비즈",
    handle: "@chosunbiz",
    category: "증권",
    region: "kr",
    url: "https://biz.chosun.com/arc/outboundfeeds/rss/category/stock/?outputType=xml",
    domain: "biz.chosun.com",
    color: "#004b9b",
  },
  {
    id: "fnnews",
    name: "파이낸셜뉴스",
    handle: "@fnnews",
    category: "증권",
    region: "kr",
    url: "https://www.fnnews.com/rss/r20/fn_realnews_stock.xml",
    domain: "fnnews.com",
    color: "#d31145",
  },
  // ── 해외 🌐 ──
  {
    id: "investing",
    name: "Investing.com",
    handle: "@investingcom",
    category: "Stock Market",
    region: "global",
    url: "https://www.investing.com/rss/news_25.rss",
    domain: "investing.com",
    color: "#d6a012",
  },
  {
    id: "cnbc",
    name: "CNBC Markets",
    handle: "@CNBC",
    category: "Markets",
    region: "global",
    url: "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    domain: "cnbc.com",
    color: "#005594",
  },
  {
    id: "marketwatch",
    name: "MarketWatch",
    handle: "@MarketWatch",
    category: "Top Stories",
    region: "global",
    url: "https://feeds.content.dowjones.io/public/rss/mw_topstories",
    domain: "marketwatch.com",
    color: "#00a651",
  },
  {
    id: "yahoo",
    name: "Yahoo Finance",
    handle: "@YahooFinance",
    category: "Finance",
    region: "global",
    url: "https://finance.yahoo.com/news/rssindex",
    domain: "finance.yahoo.com",
    color: "#6001d2",
  },
  {
    id: "bloomberg",
    name: "Bloomberg",
    handle: "@business",
    category: "Markets",
    region: "global",
    url: "https://feeds.bloomberg.com/markets/news.rss",
    domain: "bloomberg.com",
    color: "#2b2b2b",
  },
  {
    id: "ft",
    name: "Financial Times",
    handle: "@FT",
    category: "Markets",
    region: "global",
    url: "https://www.ft.com/markets?format=rss",
    domain: "ft.com",
    color: "#990f3d",
  },
  {
    id: "seekingalpha",
    name: "Seeking Alpha",
    handle: "@SeekingAlpha",
    category: "Stock Analysis",
    region: "global",
    url: "https://seekingalpha.com/feed.xml",
    domain: "seekingalpha.com",
    color: "#ff6600",
  },
  {
    id: "nasdaq",
    name: "Nasdaq",
    handle: "@Nasdaq",
    category: "Markets",
    region: "global",
    url: "https://www.nasdaq.com/feed/rssoutbound?category=Markets",
    domain: "nasdaq.com",
    color: "#0092cf",
  },
  {
    id: "businessinsider",
    name: "Business Insider",
    handle: "@BInsider",
    category: "Markets",
    region: "global",
    url: "https://markets.businessinsider.com/rss/news",
    domain: "businessinsider.com",
    color: "#2255ff",
  },
  {
    id: "fool",
    name: "Motley Fool",
    handle: "@themotleyfool",
    category: "Investing",
    region: "global",
    url: "https://www.fool.com/feeds/index.aspx",
    domain: "fool.com",
    color: "#5a2d82",
  },
  {
    id: "bbc",
    name: "BBC Business",
    handle: "@BBCBusiness",
    category: "Business",
    region: "global",
    url: "https://feeds.bbci.co.uk/news/business/rss.xml",
    domain: "bbc.com",
    color: "#bb1919",
  },
];

export const SOURCE_MAP: Record<string, Source> = Object.fromEntries(
  SOURCES.map((s) => [s.id, s]),
);

export function sourcesByIds(ids: string[]): Source[] {
  return ids.map((id) => SOURCE_MAP[id]).filter(Boolean);
}
